server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    listener:
      missing-topics-fatal: false

logging:
  level:
    org.apache.kafka: DEBUG
    com.example.notificationservice: INFO